import { Controller, Post, Body, UseGuards, Request, Get, Param } from '@nestjs/common';
import { ReferralsService } from './referrals.service';
import { CreateReferralDto } from './dto/create-referral.dto';
import { AuthGuard } from '@nestjs/passport';
import { ApiBearerAuth, ApiOperation, ApiTags, ApiResponse } from '@nestjs/swagger';

@ApiTags('Referrals')
@ApiBearerAuth()
@UseGuards(AuthGuard('jwt'))
@Controller('referrals')
export class ReferralsController {
    constructor(private readonly referralsService: ReferralsService) { }

    @Post()
    @ApiOperation({ summary: 'Create a new referral invite' })
    @ApiResponse({ status: 201, description: 'Referral created' })
    create(@Request() req, @Body() createReferralDto: CreateReferralDto) {
        return this.referralsService.create(req.user.userId, createReferralDto);
    }

    @Get('my')
    @ApiOperation({ summary: 'List all referrals generated by current partner' })
    findAll(@Request() req) {
        return this.referralsService.findAllForPartner(req.user.userId);
    }

    @Post('check-qualification-test/:userId/:amount')
    @ApiOperation({ summary: 'Internal Dev Test: Manually trigger qualification check' })
    testQualify(@Param('userId') userId: string, @Param('amount') amount: string) {
        // FOR DEMO PURPOSES ONLY
        return this.referralsService.processQualifyingOrder(userId, parseFloat(amount));
    }
}
